// Test clients for RLS behaviour tests (PLAN-REVIEW Part B).
// Four supabase-js clients against the LOCAL stack: anon (no session) plus
// alice (admin), bob (member1), chris (member2 — intentionally unmapped).
// Reads local URL + anon key from env (populated by scripts/test-env.sh).
import { createClient, type SupabaseClient } from '@supabase/supabase-js'

const URL = process.env.SUPABASE_URL
const ANON = process.env.SUPABASE_ANON_KEY
if (!URL || !ANON) {
  throw new Error(
    'SUPABASE_URL / SUPABASE_ANON_KEY not set. Run `source scripts/test-env.sh` ' +
      '(needs the local stack up: `npm run db:start`).',
  )
}

// Real user ids are generated by the admin API at seed time and written here.
import seedIds from './seed-ids.json' with { type: 'json' }

export const SEED = {
  admin: { email: 'alice@test.local', id: seedIds.admin, member: 'Alice' },
  member1: { email: 'bob@test.local', id: seedIds.member1, member: 'Bob' },
  member2: { email: 'chris@test.local', id: seedIds.member2, member: null },
  password: 'password123',
}

/** A fresh anonymous client (no session). */
export function anonClient(): SupabaseClient {
  return createClient(URL!, ANON!, { auth: { persistSession: false, autoRefreshToken: false } })
}

/** Service-role client — bypasses RLS. For asserting true DB state in tests
 *  (never a thing the app ships; profiles SELECT is own-only even for admins). */
export function serviceClient(): SupabaseClient {
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY
  if (!key) throw new Error('SUPABASE_SERVICE_ROLE_KEY not set')
  return createClient(URL!, key, { auth: { persistSession: false, autoRefreshToken: false } })
}

/** A client signed in as the given seed user. */
export async function signedInClient(email: string): Promise<SupabaseClient> {
  const c = createClient(URL!, ANON!, { auth: { persistSession: false, autoRefreshToken: false } })
  const { error } = await c.auth.signInWithPassword({ email, password: SEED.password })
  if (error) throw new Error(`sign-in failed for ${email}: ${error.message}`)
  return c
}

/** PostgREST error code for an RLS/permission denial on write. */
export const RLS_DENIED = '42501'
