-- Initial schema for Erhvervsklubben — reproduces prod project urlabzyihqrsdeasvrfe
-- verbatim (schema + RLS + functions + signup trigger).
-- Source of truth: docs/schema-snapshot-2026-07-23.sql (captured read-only).
-- Task T010. Verified by the parity check (T011) against the prod snapshot.

-- ============================================================ enum
create type public.user_role as enum ('admin', 'user');

-- ============================================================ tables
create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  role public.user_role not null default 'user',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table public.news (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  excerpt text not null,
  author text not null,
  date date not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.events (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  date date not null,
  time text not null,
  location text not null,
  description text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.attendance_records (
  id integer primary key generated by default as identity,
  meeting_number integer not null,
  lead text not null,
  pre_location text,
  main_location text not null,
  post_location text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table public.attendances (
  id integer primary key generated by default as identity,
  record_id integer references public.attendance_records (id) on delete cascade,
  member_name text not null,
  attended boolean default false
);

create table public.event_evaluations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  record_id integer not null references public.attendance_records (id) on delete cascade,
  pre_surroundings_rating integer not null check (pre_surroundings_rating between 1 and 5),
  pre_surroundings_comment text,
  pre_drinks_rating integer not null check (pre_drinks_rating between 1 and 5),
  pre_drinks_comment text,
  location_surroundings_rating integer not null check (location_surroundings_rating between 1 and 5),
  location_surroundings_comment text,
  location_food_rating integer not null check (location_food_rating between 1 and 5),
  location_food_comment text,
  location_value_rating integer not null check (location_value_rating between 1 and 5),
  location_value_comment text,
  post_value_rating integer not null check (post_value_rating between 1 and 5),
  post_value_comment text,
  lead_agenda_rating integer not null check (lead_agenda_rating between 1 and 5),
  lead_agenda_comment text,
  lead_flow_rating integer not null check (lead_flow_rating between 1 and 5),
  lead_flow_comment text,
  lead_overall_rating integer not null check (lead_overall_rating between 1 and 5),
  lead_overall_comment text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.user_member_mapping (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references public.profiles (id) on delete cascade,
  member_name text not null,
  created_at timestamptz not null default now()
);

-- ============================================================ functions
-- SECURITY DEFINER so policies can read a caller's role without recursing on
-- profiles' own RLS (get_user_role) / can insert a profile as the auth admin
-- during signup (handle_new_user).
create or replace function public.get_user_role(user_id uuid)
  returns public.user_role
  language sql
  stable
  security definer
as $$
  select role from public.profiles where id = user_id;
$$;

create or replace function public.handle_new_user()
  returns trigger
  language plpgsql
  security definer
  set search_path to 'public'
as $$
begin
  insert into public.profiles (id, role)
  values (new.id, 'user');
  return new;
end;
$$;

-- ============================================================ signup trigger (on auth.users)
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ============================================================ enable RLS on all 7 tables
alter table public.profiles            enable row level security;
alter table public.news                enable row level security;
alter table public.events              enable row level security;
alter table public.attendance_records  enable row level security;
alter table public.attendances         enable row level security;
alter table public.event_evaluations   enable row level security;
alter table public.user_member_mapping enable row level security;

-- ============================================================ policies (verbatim)

-- attendance_records
create policy "Allow authenticated users to view attendance_records"
  on public.attendance_records for select to authenticated using (true);
create policy "Allow admin users to insert attendance_records"
  on public.attendance_records for insert to authenticated
  with check (get_user_role(auth.uid()) = 'admin'::user_role);
create policy "Allow admin users to update attendance_records"
  on public.attendance_records for update to authenticated
  using (get_user_role(auth.uid()) = 'admin'::user_role);
create policy "Allow admin users to delete attendance_records"
  on public.attendance_records for delete to authenticated
  using (get_user_role(auth.uid()) = 'admin'::user_role);

-- attendances
create policy "Allow authenticated users to view attendances"
  on public.attendances for select to authenticated using (true);
create policy "Allow admin users to manage attendances"
  on public.attendances for all to authenticated
  using (get_user_role(auth.uid()) = 'admin'::user_role)
  with check (get_user_role(auth.uid()) = 'admin'::user_role);

-- event_evaluations (per-user; note: no DELETE policy → nobody can delete)
create policy "Users can view their own evaluations"
  on public.event_evaluations for select using (auth.uid() = user_id);
create policy "Users can create their own evaluations"
  on public.event_evaluations for insert with check (auth.uid() = user_id);
create policy "Users can update their own evaluations"
  on public.event_evaluations for update using (auth.uid() = user_id);

-- events (public read, admin write)
create policy "Enable read access for all users"
  on public.events for select using (true);
create policy "Enable insert for admin users only"
  on public.events for insert
  with check ((select profiles.role from profiles where profiles.id = auth.uid()) = 'admin'::user_role);
create policy "Enable update for admin users only"
  on public.events for update
  using ((select profiles.role from profiles where profiles.id = auth.uid()) = 'admin'::user_role);
create policy "Enable delete for admin users only"
  on public.events for delete
  using ((select profiles.role from profiles where profiles.id = auth.uid()) = 'admin'::user_role);

-- news (public read, admin write)
create policy "Enable read access for all users"
  on public.news for select using (true);
create policy "Enable insert for admin users only"
  on public.news for insert
  with check ((select profiles.role from profiles where profiles.id = auth.uid()) = 'admin'::user_role);
create policy "Enable update for admin users only"
  on public.news for update
  using ((select profiles.role from profiles where profiles.id = auth.uid()) = 'admin'::user_role);
create policy "Enable delete for admin users only"
  on public.news for delete
  using ((select profiles.role from profiles where profiles.id = auth.uid()) = 'admin'::user_role);

-- profiles
create policy "Users can read own profile"
  on public.profiles for select using (auth.uid() = id);
create policy "Only admins can update profiles"
  on public.profiles for update
  using (auth.uid() in (select profiles_1.id from profiles profiles_1 where profiles_1.role = 'admin'::user_role));

-- user_member_mapping
create policy "Users can view their own mapping"
  on public.user_member_mapping for select using (auth.uid() = user_id);
create policy "Admins can manage all mappings"
  on public.user_member_mapping for all
  using (get_user_role(auth.uid()) = 'admin'::user_role)
  with check (get_user_role(auth.uid()) = 'admin'::user_role);

-- ============================================================ grants
-- PostgREST roles need table grants; RLS above still governs which ROWS each
-- role sees (broad grant + RLS is the standard Supabase model). Hosted Supabase
-- adds these automatically — a hand-authored migration must include them.
grant usage on schema public to anon, authenticated, service_role;
grant all on all tables in schema public to anon, authenticated, service_role;
grant all on all sequences in schema public to anon, authenticated, service_role;
grant all on all routines in schema public to anon, authenticated, service_role;
alter default privileges in schema public
  grant all on tables to anon, authenticated, service_role;
alter default privileges in schema public
  grant all on sequences to anon, authenticated, service_role;
